## Import Numpy

Import `NumPy` with the alias `np`.

In [1]:
import numpy as np

# Indexing a Single Element

Let's start by creating a three-dimensional array. 

In [2]:
a3 = np.random.randint(0, 10, [2,3,4])
print(a3)

[[[1 2 6 4]
  [1 0 1 0]
  [1 4 5 3]]

 [[0 6 6 6]
  [8 3 3 4]
  [2 9 1 1]]]


The ith value (counting from zero) can be accessed by specifying the desired index in square brackets.

In [3]:
print("The element at the bottom right of the first array is:", a3[0, 2, 3])
print("The element at the middle left of the second array is:", a3[1, 1, 0])

The element at the bottom right of the first array is: 3
The element at the middle left of the second array is: 8


To index from the end of the array can be accessed with negative indices.

In [4]:
print("The element at the bottom right of the first array is:", a3[-2, -1, -1])
print("The element at the middle left of the second array is:", a3[-1, -2, -4])

The element at the bottom right of the first array is: 3
The element at the middle left of the second array is: 8


Indexing allows to replace values.

In [5]:
a3[-2, -1, -1]=99
a3[-1, -2, -4]=99
print("The element at the bottom right of the first array is now:", a3[-2, -1, -1])
print("The element at the middle left of the second array is now:", a3[-1, -2, -4])

The element at the bottom right of the first array is now: 99
The element at the middle left of the second array is now: 99


Note that np arrays can contain only one type of data. This implies, for example, that if you insert a float into an integer array, the float will be truncated.

In [6]:
a1 = np.arange(5)
a1[2] = 99.99999
print(a1)

[ 0  1 99  3  4]


# Indexing Multiple Elements

Let's start by creating an array.

In [7]:
a1 = np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


Arrays can be sliced to access subarrays, i.e. multiple elements at one time. The general notation is `x[start:stop:step]` and, if any elements is unspecified, they default to start=0, stop=size of dimension, step=1.

Select the elements up to index 5.

In [8]:
print(a1[:5])

[0 1 2 3 4]


Select the elements from index 5.

In [9]:
print(a1[5:])

[5 6 7 8 9]


Select the elements from index 4 up to 7.

In [10]:
print(a1[4:7])

[4 5 6]


Select every other element.

In [11]:
print(a1[::2])

[0 2 4 6 8]


Select every other element, starting at index 1.

In [12]:
print(a1[1::2])

[1 3 5 7 9]


Select every other element going backwards from the last.

In [13]:
print(a1[::-2])

[9 7 5 3 1]


Select every other element going backwards starting from index 8. 

In [14]:
print(a1[8::-2])

[8 6 4 2 0]


Reverse an array.

In [15]:
print(a1[::-1])

[9 8 7 6 5 4 3 2 1 0]


Let's now create a multi-dimensional array to understand how to extract multi-dimensional subarrays.

In [16]:
a3 = np.random.randint(0, 10, [6,5])
print(a3)

[[6 9 8 7 4]
 [7 3 4 3 4]
 [1 4 8 1 8]
 [7 0 0 9 7]
 [5 1 8 4 2]
 [6 6 7 4 4]]


Select the first two rows and the first two columns.

In [17]:
print(a3[:2, :2])

[[6 9]
 [7 3]]


Select all rows and columns up to index 3.

In [18]:
print(a3[:, :3])

[[6 9 8]
 [7 3 4]
 [1 4 8]
 [7 0 0]
 [5 1 8]
 [6 6 7]]


Select all rows and columns from index 2.

In [19]:
print(a3[:, 2:])

[[8 7 4]
 [4 3 4]
 [8 1 8]
 [0 9 7]
 [8 4 2]
 [7 4 4]]


Select all rows and columns from index 1 up to index 3.

In [20]:
print(a3[:, 1:3])

[[9 8]
 [3 4]
 [4 8]
 [0 0]
 [1 8]
 [6 7]]


Select every other column.

In [21]:
print(a3[:, ::2])

[[6 8 4]
 [7 4 4]
 [1 8 8]
 [7 0 7]
 [5 8 2]
 [6 7 4]]


Select every other column, starting at index 1.

In [22]:
print(a3[:, 1::2])

[[9 7]
 [3 3]
 [4 1]
 [0 9]
 [1 4]
 [6 4]]


Select every other column going backwards from the last.

In [23]:
print(a3[:, ::-2])

[[4 8 6]
 [4 4 7]
 [8 8 1]
 [7 0 7]
 [2 8 5]
 [4 7 6]]


Select every other column going backwards starting from index 2.

In [24]:
print(a3[:, 2::-2])

[[8 6]
 [4 7]
 [8 1]
 [0 7]
 [8 5]
 [7 6]]


Reverse the column of the array.

In [25]:
print(a3[:,::-1])

[[4 7 8 9 6]
 [4 3 4 3 7]
 [8 1 8 4 1]
 [7 9 0 0 7]
 [2 4 8 1 5]
 [4 4 7 6 6]]


Reverse together both subarray dimensions

In [26]:
print(a3[::-1, ::-1])

[[4 4 7 6 6]
 [2 4 8 1 5]
 [7 9 0 0 7]
 [8 1 8 4 1]
 [4 3 4 3 7]
 [4 7 8 9 6]]


# Subarrays are Views not Copies

A very important characteristic of subarrays is that they return views, not copies of the array.

Create a multi-dimensional array.

In [27]:
a3 = np.zeros([6,5])
print(a3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Extract a 2x2 subarray.

In [28]:
a3_sub = a3[:2, :2]
print(a3_sub)

[[0. 0.]
 [0. 0.]]


If this subarray is modified, the original one is changed.

In [29]:
a3_sub[0, 0] = 1
a3_sub[1, 0] = 1
a3_sub[1, 1] = 1
a3_sub[0, 1] = 1
print(a3_sub)

[[1. 1.]
 [1. 1.]]


In [30]:
print(a3)

[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Copies of Arrays

Create a copy (not a view) of a subarray.

Create a multi-dimensional array.

In [31]:
a3 = np.zeros([6,5])
print(a3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Extract a 2x2 subarray.

In [32]:
a3_sub_copy = a3[:2, :2].copy()
print(a3_sub_copy)

[[0. 0.]
 [0. 0.]]


If this subarray is modified, the original one is not changed.

In [33]:
a3_sub_copy[0, 0] = 1
a3_sub_copy[1, 0] = 1
a3_sub_copy[1, 1] = 1
a3_sub_copy[0, 1] = 1
print(a3_sub_copy)

[[1. 1.]
 [1. 1.]]


In [34]:
print(a3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
