## Import Numpy

Import `NumPy` with the alias `np`.

In [1]:
import numpy as np

# Array Reshaping

Create a one dimensional array.

In [2]:
a1 = np.arange(9)
print(a1)

[0 1 2 3 4 5 6 7 8]


Reshape it into a 3x3 array.

In [3]:
a1_res = a1.reshape(3, 3)
print(a1_res)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a row vector using reshape.

In [4]:
a1_row = a1.reshape(1, 9)
print(a1_row)

[[0 1 2 3 4 5 6 7 8]]


Create a column vector using reshape.

In [5]:
a1_col = a1.reshape(9, 1)
print(a1_col)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


Note the differences.

In [6]:
print("The number of dimensions of a1 is:", np.ndim(a1))
print("The shape of a1 is:", np.shape(a1))
print("The number of dimensions of a1_row is:", np.ndim(a1_row))
print("The shape of a1_row is:", np.shape(a1_row))
print("The number of dimensions of a1_col is:", np.ndim(a1_col))
print("The shape of a1_col is:", np.shape(a1_col))

The number of dimensions of a1 is: 1
The shape of a1 is: (9,)
The number of dimensions of a1_row is: 2
The shape of a1_row is: (1, 9)
The number of dimensions of a1_col is: 2
The shape of a1_col is: (9, 1)


# Array Stacking

Create two multi-dimensional arrays.

In [7]:
a1 = np.random.randint(0, 10, (3, 3))
a2 = np.random.randint(0, 10, (3, 3))
print(a1)
print()
print(a2)

[[1 1 2]
 [1 7 7]
 [8 4 5]]

[[7 4 0]
 [6 8 0]
 [2 1 4]]


Concatenate the two arrays along the first axis.

In [8]:
a12_first = np.concatenate([a1, a2], axis=0)
print(a12_first)

[[1 1 2]
 [1 7 7]
 [8 4 5]
 [7 4 0]
 [6 8 0]
 [2 1 4]]


Or

In [9]:
a12_first2 = np.vstack([a1, a2])
print(a12_first2)

[[1 1 2]
 [1 7 7]
 [8 4 5]
 [7 4 0]
 [6 8 0]
 [2 1 4]]


Concatenate the two arrays along the second axis.

In [10]:
a12_second = np.concatenate([a1, a2], axis=1)
print(a12_second)

[[1 1 2 7 4 0]
 [1 7 7 6 8 0]
 [8 4 5 2 1 4]]


Or

In [11]:
a12_second2 = np.hstack([a1, a2])
print(a12_second2)

[[1 1 2 7 4 0]
 [1 7 7 6 8 0]
 [8 4 5 2 1 4]]


# Array Splitting

Create a multi-dimensional array.

In [12]:
a = np.random.randint(0, 10, (3,6))
print(a)

[[0 8 5 4 7 6]
 [3 3 7 8 1 1]
 [5 3 4 0 8 6]]


Split the array along the first axis at the index position 1.

In [13]:
a_1_first, a_2_first = np.split(a, [1], axis=0)
print(a_1_first)
print()
print(a_2_first)

[[0 8 5 4 7 6]]

[[3 3 7 8 1 1]
 [5 3 4 0 8 6]]


Or

In [14]:
a_1_first2, a_2_first2 = np.vsplit(a, [1])
print(a_1_first)
print()
print(a_2_first)

[[0 8 5 4 7 6]]

[[3 3 7 8 1 1]
 [5 3 4 0 8 6]]


Split the array along the second axis at the index positions 2.

In [15]:
a_1_second, a_2_second = np.split(a, [2], axis=1)
print(a_1_second)
print()
print(a_2_second)

[[0 8]
 [3 3]
 [5 3]]

[[5 4 7 6]
 [7 8 1 1]
 [4 0 8 6]]


Or

In [16]:
a_1_second2, a_2_second2 = np.hsplit(a, [2])
print(a_1_second2)
print()
print(a_2_second2)

[[0 8]
 [3 3]
 [5 3]]

[[5 4 7 6]
 [7 8 1 1]
 [4 0 8 6]]
