## Import Numpy

Import `NumPy` with the alias `np`.

In [1]:
import numpy as np

# Aggregation Functions

`NumPy` provides built-in aggregation functions to work with arrays, which are much more efficient than the built-in `Python` functions. Therefore, it is optimal to use the `NumPy` version of these aggregates whenever possible. 

## One-Dimensional Aggregates

Let's start by creating a one-dimensional array.

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]


Compute the sum of all the values.

In [3]:
print(np.sum(a1))

15


Compute the minimum value.

In [4]:
print(np.min(a1))

1


Compute the maximum value.

In [5]:
print(np.max(a1))

5


An alternative syntax to call these aggregation functions is to use the methods of the array object itself, as follows:

In [6]:
# Sum, min, max:
print('sum:', a1.sum(), 'min:', a1.min(), 'max:', a1.max())

sum: 15 min: 1 max: 5


## Multi-Dimensional Aggregates

Let's start by creating a multi-dimensional array.

In [7]:
a2 = np.random.randint(10, size=[3,4])
print(a2)

[[8 2 6 4]
 [1 3 9 0]
 [3 3 0 1]]


By default, `NumPy` computes aggregations functions over all elements in the array.

Compute the sum of all the values.

In [8]:
print(np.sum(a2))

40


Compute the minimum value.

In [9]:
print(np.min(a2))

0


Compute the maximum value.

In [10]:
print(np.max(a2))

9


To compute an aggregation function along an axis, it is necessary to add the argument `axis`, which specifies the dimension that will be collapsed, i.e. the dimension along which the elements are aggreagted.

Compute the sum of all the values along each column and along each row.

In [11]:
# Columns:
print(np.sum(a2, axis=0))

# Rows:
print(np.sum(a2, axis=1))

[12  8 15  5]
[20 13  7]


Compute the minimum value along each column and along each row.

In [12]:
# Columns:
print(np.min(a2, axis=0))

# Rows:
print(np.min(a2, axis=1))

[1 2 0 0]
[2 0 0]


Compute the maximum value along each column and along each row.

In [13]:
# Columns:
print(np.max(a2, axis=0))

# Rows:
print(np.max(a2, axis=1))

[8 3 9 4]
[8 9 3]


## Other Usefult Functions

Compute product of elements: `np.prod`, compute mean of elements: `np.mean`, compute median of elements: `np.median`, compute standard deviation: `np.std`, compute variance: `np.var`, find index of minimum value: `np.argmin`, find index of maximum value: `np.argmax`, compute rank-based statistics of elements: `np.percentile`, evaluate whether any elements are true: `np.any`, evaluate whether all elements are true: `np.all`.                       

## NaN Values

Most aggregation functions have a `NaN`-safe counterpart that computes the result ignoring the missing values, which are denoted by the special IEEE floating-point `NaN` value.