## Import Numpy 

Import NumPy with the alias np.

In [1]:
import numpy as np

# Create Arrays from Python Lists

Create an array.

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

Arrays must contain the same data type. If types do not match, np tries to upcast (here, integers are up-cast to floating point).

In [3]:
np.array([1, 2, 3.1])

array([1. , 2. , 3.1])

Explicitly set the data type of the resulting array.

In [4]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

Create a multi-dimensional array.

In [5]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Create Arrays from Scratch

Create a float array filled with zeros.

In [6]:
np.zeros(3, dtype='float')

array([0., 0., 0.])

Create a float array filled with ones.

In [7]:
np.ones(3, dtype='float')

array([1., 1., 1.])

Create an array filled with 3.1415.

In [8]:
np.full(3, 3.1415)

array([3.1415, 3.1415, 3.1415])

Create a float array filled with a linear sequence from 0 to 10 at steps of 2.

In [9]:
np.arange(0, 10, 2, dtype='float')

array([0., 2., 4., 6., 8.])

Create an array of five values evenly spaced between 0 and 10.

In [10]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Create an array of uniformely distributed random numbers between [0, 1).

In [11]:
np.random.random(3)

array([0.14103921, 0.75277941, 0.90876054])

Create an array of normally distributed random numbers with mean 0 and standard deviation 1.

In [12]:
np.random.normal(0, 1, 3)

array([-0.94816357,  0.23920572,  1.01075816])

Create an array of random integers in the interval [0, 10).

In [13]:
np.random.randint(0, 10, 3)

array([8, 7, 8])

Create an identity matrix.

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])