## Import Numpy

Import NumPy with the alias np.

In [1]:
import numpy as np

# Array Attributes

Let's start by creating a three-dimensional array.

In [2]:
a3 = np.random.randint(0, 10, (2,3,4))
print(a3)

[[[7 9 9 8]
  [7 6 4 6]
  [8 4 3 3]]

 [[0 9 4 3]
  [5 8 8 3]
  [5 0 1 7]]]


Return the number of dimensions.

In [3]:
print('a3 ndim:', a3.ndim)

a3 ndim: 3


Return the shape.

In [4]:
print('a3 shape:', a3.shape)

a3 shape: (2, 3, 4)


Return the size, i.e. the product of the elements in the shape.

In [5]:
print('a3 size:', a3.size)

a3 size: 24


Return the data type.

In [6]:
print('a3 dtype:', a3.dtype)

a3 dtype: int64


Return the itemsize, which lists the size (in bytes) of each element.

In [7]:
print('a3 itemsize (in bytes):', a3.itemsize)

a3 itemsize (in bytes): 8


Return nbytes, which lists the total size (in bytes) of the array, i.e. the product of itemsize and size

In [8]:
print('a3 nbytes (in bytes):', a3.nbytes)

a3 nbytes (in bytes): 192
