# NumPy - Array Indexing and Slicing


---



In [ ]:
import numpy as np

## Indexing arrays

**Access a single value** of an array by specifying its index in square brackets.

In [ ]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("\nThe element at index [0,1] is:", array_a[0, 1])

[[5 9 4 4]
 [9 7 6 1]
 [8 3 2 8]]

The element at index [0,1] is: 9


In [ ]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("\nThe element at index [-1, -2] is:", array_a[-1, -2])

[[4 4 1 8]
 [3 9 1 4]
 [5 9 9 6]]

The element at index [-1, -2] is: 9


**Modify a single value** of an array by specifying its index in square brackets.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])

print(array_a)
print("\nThe original value at index [0,0] is:", array_a[0, 0])
print()

array_a[0, 0] = 0
print(array_a)
print("\nThe modified value at index [0,0] is:", array_a[0, 0])

[[7 8 3 5]
 [2 8 1 3]
 [5 9 6 6]]

The original value at index [0,0] is: 7

[[0 8 3 5]
 [2 8 1 3]
 [5 9 6 6]]

The modified value at index [0,0] is: 0


Arrays can contain only **one type of data**. This implies, for example, that if you insert a float into an integer array, the float will be truncated.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])

print(array_a)
print("\nThe original value at index [0,0] is:", array_a[0, 0])
print()

array_a[0, 0] = 0.99
print(array_a)
print("\nThe modified value at index [0,0] is:", array_a[0, 0])

[[2 7 4 5]
 [5 3 6 9]
 [8 1 5 3]]

The original value at index [0,0] is: 2

[[0 7 4 5]
 [5 3 6 9]
 [8 1 5 3]]

The modified value at index [0,0] is: 0


## Slicing arrays
**Slice an array** by specifying the indexes in square brackets, using the general notation [start:stop:step] (default values: start=0, stop=shape, step=1). Note that the stop value is excluded when specified.

In [ ]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("\nThe slice at indexes [:2, :3] is:\n", array_a[:2, :3])
print("The slice at indexes [1:, 1:] is:\n", array_a[1:, 1:])
print("The slice at indexes [1:3, 1:3] is:\n", array_a[1:3, 1:3])

[[8 8 3 9]
 [2 6 4 3]
 [3 3 1 3]]

The slice at indexes [:2, :3] is:
 [[8 8 3]
 [2 6 4]]
The slice at indexes [1:, 1:] is:
 [[6 4 3]
 [3 1 3]]
The slice at indexes [1:3, 1:3] is:
 [[6 4]
 [3 1]]


In [ ]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("\nThe slice at indexes [:-1, :-1] is:\n", array_a[:-1, :-1])
print("The slice at indexes [-2:, -3:] is:\n", array_a[-2:, -3:])
print("The slice at indexes [-2:, -3:-1] is:\n", array_a[-2:, -3:-1])

[[3 1 1 2]
 [0 4 1 9]
 [2 1 3 3]]

The slice at indexes [:-1, :-1] is:
 [[3 1 1]
 [0 4 1]]
The slice at indexes [-2:, -3:] is:
 [[4 1 9]
 [1 3 3]]
The slice at indexes [-2:, -3:-1] is:
 [[4 1]
 [1 3]]


**Select an entire row or column**, using the column sign. 

In [ ]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("\nThe slice indexes [:, 1] is:\n", array_a[:, 1])
print("The slice at indexes [1, :] is:\n", array_a[1, :])

[[6 0 7 9]
 [1 8 1 2]
 [6 8 1 2]]

The slice indexes [:, 1] is:
 [0 8 8]
The slice at indexes [1, :] is:
 [1 8 1 2]


**Select every other element**, using step=+2/-2.

In [ ]:
array_a = np.arange(0, 10, 1)
print(array_a)

print("Select every other element:", array_a[::2])
print("Select every other element, going backwards:", array_a[::-2])
print("Select every other element, starting at index 1:", array_a[1::2])
print("Select every other element, going backwards, starting at index 8:", array_a[8::-2])

[0 1 2 3 4 5 6 7 8 9]
Select every other element: [0 2 4 6 8]
Select every other element, going backwards: [9 7 5 3 1]
Select every other element, starting at index 1: [1 3 5 7 9]
Select every other element, going backwards, starting at index 8: [8 6 4 2 0]


**Reverse an array**, using step=-1

In [ ]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("Reverse the rows of the array:\n", array_a[::-1, :])
print("Reverse the row and columns of the array:\n", array_a[::-1, ::-1])

[[0 6 4 8]
 [4 8 7 1]
 [4 6 0 2]]
Reverse the rows of the array:
 [[4 6 0 2]
 [4 8 7 1]
 [0 6 4 8]]
Reverse the row and columns of the array:
 [[2 0 6 4]
 [1 7 8 4]
 [8 4 6 0]]


## Views and copies

Subarrays return **views not copies** of the array. Therefore, if a subarray is modified, the original array changes as well.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n",array_a)

array_b = array_a[:2, :2]
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0

print("\nModified array:\n",array_a)

Original array:
 [[4 5 8 7]
 [4 3 7 7]
 [9 8 2 6]]

Modified array:
 [[0 0 8 7]
 [0 0 7 7]
 [9 8 2 6]]


**Create a copy** of a subarray using `.copy`

In [16]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n", array_a)

array_b = array_a[:2, :2].copy()
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0
print("\nModified array:\n", array_b)

print("\nVerify array:\n", array_a)

Original array:
 [[6 6 2 5]
 [2 7 3 3]
 [5 7 3 6]]

Modified array:
 [[0 0]
 [0 0]]

Verify array:
 [[6 6 2 5]
 [2 7 3 3]
 [5 7 3 6]]
