# NumPy - Array Creation and Attributes


---



In [1]:
import numpy as np

## Creating arrays

Create an array of **constant values** from a list using `np.array`

In [34]:
array_a = np.array([1, 2, 3], dtype=np.int)
print(array_a, "\n shape =", array_a.shape)

array_b = np.array([[1, 2, 3]], dtype=np.int)
print("\n", array_b, "\n shape =", array_b.shape)

array_c = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int)
print("\n", array_c, "\n shape =", array_c.shape)



[1 2 3] 
 shape = (3,)

 [[1 2 3]] 
 shape = (1, 3)

 [[1 2 3]
 [4 5 6]] 
 shape = (2, 3)


Create an array of **zeros** using `np.zeros`


In [42]:
array_a = np.zeros(shape=(3,), dtype=np.int)
print(array_a)

[0 0 0]


Create an array of **ones** using `np.ones`

In [43]:
array_a = np.ones(shape=(3,), dtype=np.int)
print(array_a)

[1 1 1]


Create an array of **repeated values** using `np.full`

In [45]:
array_a = np.full(shape=(3,), fill_value=9)
print(array_a)

[9 9 9]


Create an array of **equally spaced values** between 0 and 10 at steps of 2 using `np.arange`

In [11]:
array_a = np.arange(0, 12, 2, dtype=np.int)
print(array_a)

[ 0  2  4  6  8 10]


Create an array of **evenly spaced values** between 0 and 10 using `np.linspace`

In [12]:
array_a = np.linspace(0, 10, 6, dtype=np.int)
print(array_a)

[ 0  2  4  6  8 10]


Create an array of **random numbers** using `np.random`

In [16]:
array_a = np.random.randint(0, 10, size=(3,))
print(array_a)

array_b = np.random.uniform(0, 1, size=(3,))
print(array_b)

array_c = np.random.normal(0, 1, size=(3,))
print(array_c)

[8 2 7]
[0.80411647 0.79920625 0.53629859]
[0.54032465 1.46538507 0.22741439]


Create an array of an **identity matrix** using `np.eye`

In [17]:
array_a = np.eye(3)
print(array_a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array attributes

Return the **number of dimensions** of an array using `.ndim`

In [24]:
array_a = np.random.randint(0, 10, [2, 3, 4])
print(array_a.ndim)

3


Return the **shape** of an array using `.shape`

In [25]:
array_a = np.random.randint(0, 10, [2, 3, 4])
print(array_a.shape)

(2, 3, 4)


Return the **size** of an array (i.e. the product of the elements in the shape) using `.shape`

In [26]:
array_a = np.random.randint(0, 10, [2, 3, 4])
print(array_a.size)

24


Return the **data type** of an array using `.dtype`

In [27]:
array_a = np.random.randint(0, 10, [2, 3, 4])
print(array_a.dtype)

int64
