# NumPy - Operations


---

In [2]:
import numpy as np

## Manipulating arrays

**Reshape an array** using `np.reshape`

In [10]:
array_a = np.arange(1, 10, 1)
print("Shape =", array_a.shape, "\n", array_a)

array_b = np.reshape(array_a, [1, 9])
print("Shape =", array_b.shape, "\n", array_b)

array_c = np.reshape(array_a, [9, 1])
print("Shape =", array_c.shape, "\n", array_c)

array_d = np.reshape(array_a, [3, 3])
print("Shape =", array_d.shape, "\n", array_d)

Shape = (9,) 
 [1 2 3 4 5 6 7 8 9]
Shape = (1, 9) 
 [[1 2 3 4 5 6 7 8 9]]
Shape = (9, 1) 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape = (3, 3) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Concatenate arrays** using `np.concatenate`

In [16]:
array_a = np.full([2, 3], 0)
print("array_a:\n", array_a)

array_b = np.full([2, 3], 1)
print("array_b:\n", array_b)

array_c = np.concatenate([array_a, array_b], axis=1)
print("array_c:\n", array_c)

array_d = np.concatenate([array_a, array_b], axis=0)
print("array_d:\n", array_d)

array_a:
 [[0 0 0]
 [0 0 0]]
array_b:
 [[1 1 1]
 [1 1 1]]
array_c:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
array_d:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


**Split an array** using `np.split`

In [25]:
array_a = np.random.randint(0, 10, [3,4])
print("array_a:\n", array_a)

array_b, array_c = np.split(array_a, [2], axis=1)
print("array_b:\n", array_b, "\narray_c:\n", array_c)

array_d, array_e = np.split(array_a, [2], axis=0)
print("array_d:\n", array_d, "\narray_e:\n", array_e)

array_a:
 [[0 0 4 2]
 [9 6 7 7]
 [3 1 2 1]]
array_b:
 [[0 0]
 [9 6]
 [3 1]] 
array_c:
 [[4 2]
 [7 7]
 [2 1]]
array_d:
 [[0 0 4 2]
 [9 6 7 7]] 
array_e:
 [[3 1 2 1]]
