# NumPy - Array Indexing and Copying


---



In [7]:
import numpy as np

## Indexing single elements

**Access a value** of an array by specifying its index in square brackets.

In [3]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("The element at index [0,0] (row=1, col=1) is:", array_a[0, 0])
print("The element at index [2,3] (row=3, col=4) is:", array_a[2, 3])

[[4 9 9 6]
 [7 6 3 8]
 [4 9 1 4]]
The element at the index [0,0] (row=1, col=1) is: 4
The element at the index [2,3] (row=3, col=4) is: 4


In [4]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("The element at index [-3, -4] (row=-3, col=-4) is:", array_a[0, 0])
print("The element at index [-1, -1] (row=-1, col=-1) is:", array_a[2, 3])

[[8 8 2 1]
 [8 5 7 2]
 [7 9 4 6]]
The element at the index [-3, -4] (row=-3, col=-4) is: 8
The element at the index [-1, -1] (row=-1, col=-1) is: 6


## Indexing multiple elements

**Access multiple values** of an array by specifying their index in square brackets, using the general notation [start:stop:step] (default values: start=0, stop=shape, step=1). Note that the stop value is excluded when specified.

In [59]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:2, :3] (row=1 to 2, col=1 to 3) are:\n", array_a[:2, :3])
print("The elements at indexes [1:, 1:] (row=2 to 3, col=2 to 4) are:\n", array_a[1:, 1:])
print("The elements at indexes [1:3, 1:3] (row=2 to 3, col=2 to 3) are:\n", array_a[1:3, 1:3])

[[7 8 0 5]
 [7 0 7 8]
 [3 2 5 4]]
The elements at indexes [:2, :3] (row=1 to 2, col=1 to 3) are:
 [[7 8 0]
 [7 0 7]]
The elements at indexes [1:, 1:] (row=2 to 3, col=2 to 4) are:
 [[0 7 8]
 [2 5 4]]
The elements at indexes [1:3, 1:3] (row=2 to 3, col=2 to 3) are:
 [[0 7]
 [2 5]]


In [68]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:-1, :-1] (row=-3 to -2, col=-4 to -2) are:\n", array_a[:-1, :-1])
print("The elements at indexes [-2:, -3:] (row=-2 to -1, col=-3 to -1) are:\n", array_a[-2:, -3:])
print("The elements at indexes [-2:, -3:-1] (row=-2 to -1, col=-3 to -2) are:\n", array_a[-2:, -3:-1])

[[9 1 6 5]
 [1 4 6 7]
 [5 5 3 9]]
The elements at indexes [:-1, :-1] (row=-3 to -2, col=-4 to -2) are:
 [[9 1 6]
 [1 4 6]]
The elements at indexes [-2:, -3:] (row=-2 to -1, col=-3 to -1) are:
 [[4 6 7]
 [5 3 9]]
The elements at indexes [-2:, -3:-1] (row=-2 to -1, col=-3 to -2) are:
 [[4 6]
 [5 3]]


**Select all rows or columns**, using the column sign. 

In [72]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:, 1] (row=all, col=1) are:\n", array_a[:, 1])
print("The elements at indexes [1, :] (row=1, col=all) are:\n", array_a[1, :])

[[2 0 0 4]
 [2 9 6 8]
 [3 2 8 6]]
The elements at indexes [:, 1] (row=all, col=1) are:
 [0 9 2]
The elements at indexes [1, :] (row=1, col=all) are:
 [2 9 6 8]


**Select every other element**, using step=+2/-2.

In [73]:
array_a = np.arange(0, 10, 1)
print(array_a)

print("Select every other element:", array_a[::2])
print("Select every other element, going backwards:", array_a[::-2])
print("Select every other element, starting at index 1:", array_a[1::2])
print("Select every other element, going backwards, starting at index 8:", array_a[8::-2])

[0 1 2 3 4 5 6 7 8 9]
Select every other element: [0 2 4 6 8]
Select every other element, going backwards: [9 7 5 3 1]
Select every other element, starting at index 1: [1 3 5 7 9]
Select every other element, going backwards, starting at index 8: [8 6 4 2 0]


**Reverse an array**, using step=-1

In [75]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("Reverse the rows of the array:\n", array_a[::-1, :])
print("Reverse the row and columns of the array:\n", array_a[::-1, ::-1])

[[5 0 6 4]
 [5 4 8 9]
 [4 9 9 1]]
Reverse the rows of the array:
 [[4 9 9 1]
 [5 4 8 9]
 [5 0 6 4]]
Reverse the row and columns of the array:
 [[1 9 9 4]
 [9 8 4 5]
 [4 6 0 5]]


## Views and copies

**Modify a value** of an array by specifying its index in square brackets.

In [5]:
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)
print("The original value at index [0,0] is:", array_a[0, 0])

array_a[0, 0] = 0
print(array_a)
print("The modified value at index [0,0] is:", array_a[0, 0])

[[4 9 6 4]
 [7 9 2 7]
 [8 8 6 6]]
The original value at the index [0,0] is: 4
[[0 9 6 4]
 [7 9 2 7]
 [8 8 6 6]]
The modified value at the index [0,0] is: 0


Arrays can contain only **one type of data**. This implies, for example, that if you insert a float into an integer array, the float will be truncated.

In [6]:
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)
print("The original value at index [0,0] is:", array_a[0, 0])

array_a[0, 0] = 0.99
print(array_a)
print("The modified value at index [0,0] is:", array_a[0, 0])

[[5 4 4 7]
 [3 9 6 3]
 [8 5 6 4]]
The original value at the index [0,0] is: 5
[[0 4 4 7]
 [3 9 6 3]
 [8 5 6 4]]
The modified value at the index [0,0] is: 0


Subarrays return **views not copies** of the array. Therefore, if a subarray is modified, the original array changes as well.

In [79]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n",array_a)

array_b = array_a[:2, :2]
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0

print("Modified array:\n",array_a)

Original array:
 [[9 7 9 3]
 [7 5 2 7]
 [9 6 1 6]]
Modified array:
 [[0 0 9 3]
 [0 0 2 7]
 [9 6 1 6]]


**Create a copy** of a subarray

In [81]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n",array_a)

array_b = array_a[:2, :2].copy()
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0

print("Verify array:\n",array_a)

Original array:
 [[1 4 6 2]
 [9 7 5 6]
 [3 2 6 1]]
Verify array:
 [[1 4 6 2]
 [9 7 5 6]
 [3 2 6 1]]
