# NumPy - Array Indexing and Views


---



In [ ]:
import numpy as np

## Indexing single elements

**Access a value** of an array by specifying its index in square brackets.

In [ ]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("The element at index [0,0] (row=1, col=1) is:", array_a[0, 0])
print("The element at index [2,3] (row=3, col=4) is:", array_a[2, 3])

[[5 8 1 4]
 [5 3 4 1]
 [1 6 2 7]]
The element at index [0,0] (row=1, col=1) is: 5
The element at index [2,3] (row=3, col=4) is: 7


In [ ]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)

print("The element at index [-3, -4] (row=-3, col=-4) is:", array_a[-3, -4])
print("The element at index [-1, -1] (row=-1, col=-1) is:", array_a[-1, -1])

[[9 1 3 5]
 [4 6 9 9]
 [6 6 7 6]]
The element at index [-3, -4] (row=-3, col=-4) is: 9
The element at index [-1, -1] (row=-1, col=-1) is: 6


## Indexing multiple elements

**Access multiple values** of an array by specifying their index in square brackets, using the general notation [start:stop:step] (default values: start=0, stop=shape, step=1). Note that the stop value is excluded when specified.

In [ ]:
# Using forward indexing (index starts at 0)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:2, :3] (row=1 to 2, col=1 to 3) are:\n", array_a[:2, :3])
print("The elements at indexes [1:, 1:] (row=2 to 3, col=2 to 4) are:\n", array_a[1:, 1:])
print("The elements at indexes [1:3, 1:3] (row=2 to 3, col=2 to 3) are:\n", array_a[1:3, 1:3])

[[4 2 5 6]
 [6 5 8 9]
 [2 6 7 8]]
The elements at indexes [:2, :3] (row=1 to 2, col=1 to 3) are:
 [[4 2 5]
 [6 5 8]]
The elements at indexes [1:, 1:] (row=2 to 3, col=2 to 4) are:
 [[5 8 9]
 [6 7 8]]
The elements at indexes [1:3, 1:3] (row=2 to 3, col=2 to 3) are:
 [[5 8]
 [6 7]]


In [ ]:
# Using backward indexing (index starts at -1)
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:-1, :-1] (row=-3 to -2, col=-4 to -2) are:\n", array_a[:-1, :-1])
print("The elements at indexes [-2:, -3:] (row=-2 to -1, col=-3 to -1) are:\n", array_a[-2:, -3:])
print("The elements at indexes [-2:, -3:-1] (row=-2 to -1, col=-3 to -2) are:\n", array_a[-2:, -3:-1])

[[5 6 7 3]
 [3 5 2 2]
 [8 2 9 8]]
The elements at indexes [:-1, :-1] (row=-3 to -2, col=-4 to -2) are:
 [[5 6 7]
 [3 5 2]]
The elements at indexes [-2:, -3:] (row=-2 to -1, col=-3 to -1) are:
 [[5 2 2]
 [2 9 8]]
The elements at indexes [-2:, -3:-1] (row=-2 to -1, col=-3 to -2) are:
 [[5 2]
 [2 9]]


**Select all rows or columns**, using the column sign. 

In [ ]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("The elements at indexes [:, 1] (row=all, col=1) are:\n", array_a[:, 1])
print("The elements at indexes [1, :] (row=1, col=all) are:\n", array_a[1, :])

[[8 0 3 8]
 [8 8 9 7]
 [4 8 6 8]]
The elements at indexes [:, 1] (row=all, col=1) are:
 [0 8 8]
The elements at indexes [1, :] (row=1, col=all) are:
 [8 8 9 7]


**Select every other element**, using step=+2/-2.

In [ ]:
array_a = np.arange(0, 10, 1)
print(array_a)

print("Select every other element:", array_a[::2])
print("Select every other element, going backwards:", array_a[::-2])
print("Select every other element, starting at index 1:", array_a[1::2])
print("Select every other element, going backwards, starting at index 8:", array_a[8::-2])

[0 1 2 3 4 5 6 7 8 9]
Select every other element: [0 2 4 6 8]
Select every other element, going backwards: [9 7 5 3 1]
Select every other element, starting at index 1: [1 3 5 7 9]
Select every other element, going backwards, starting at index 8: [8 6 4 2 0]


**Reverse an array**, using step=-1

In [ ]:
array_a = np.random.randint(0, 10, [3,4])
print(array_a)

print("Reverse the rows of the array:\n", array_a[::-1, :])
print("Reverse the row and columns of the array:\n", array_a[::-1, ::-1])

[[9 6 7 0]
 [5 9 3 0]
 [1 6 5 8]]
Reverse the rows of the array:
 [[1 6 5 8]
 [5 9 3 0]
 [9 6 7 0]]
Reverse the row and columns of the array:
 [[8 5 6 1]
 [0 3 9 5]
 [0 7 6 9]]


## Views and copies

**Modify a value** of an array by specifying its index in square brackets.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)
print("The original value at index [0,0] is:", array_a[0, 0])

array_a[0, 0] = 0
print(array_a)
print("The modified value at index [0,0] is:", array_a[0, 0])

[[2 9 4 2]
 [3 4 9 9]
 [1 3 8 7]]
The original value at index [0,0] is: 2
[[0 9 4 2]
 [3 4 9 9]
 [1 3 8 7]]
The modified value at index [0,0] is: 0


Arrays can contain only **one type of data**. This implies, for example, that if you insert a float into an integer array, the float will be truncated.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])
print(array_a)
print("The original value at index [0,0] is:", array_a[0, 0])

array_a[0, 0] = 0.99
print(array_a)
print("The modified value at index [0,0] is:", array_a[0, 0])

[[2 8 7 2]
 [8 2 2 7]
 [8 5 2 6]]
The original value at index [0,0] is: 2
[[0 8 7 2]
 [8 2 2 7]
 [8 5 2 6]]
The modified value at index [0,0] is: 0


Subarrays return **views not copies** of the array. Therefore, if a subarray is modified, the original array changes as well.

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n",array_a)

array_b = array_a[:2, :2]
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0

print("Modified array:\n",array_a)

Original array:
 [[6 5 7 5]
 [7 8 5 2]
 [7 8 1 4]]
Modified array:
 [[0 0 7 5]
 [0 0 5 2]
 [7 8 1 4]]


**Create a copy** of a subarray

In [ ]:
array_a = np.random.randint(1, 10, [3, 4])
print("Original array:\n",array_a)

array_b = array_a[:2, :2].copy()
array_b[0,0] = 0
array_b[0,1] = 0
array_b[1,0] = 0
array_b[1,1] = 0

print("Verify array:\n",array_a)

Original array:
 [[9 9 2 2]
 [1 3 4 3]
 [9 1 9 8]]
Verify array:
 [[9 9 2 2]
 [1 3 4 3]
 [9 1 9 8]]
