# NumPy - Array Operations


---

In [2]:
import numpy as np

## Manipulating arrays

**Reshape an array** using `np.reshape`

In [10]:
array_a = np.arange(1, 10, 1)
print("Shape =", array_a.shape, "\n", array_a)

array_b = np.reshape(array_a, [1, 9])
print("Shape =", array_b.shape, "\n", array_b)

array_c = np.reshape(array_a, [9, 1])
print("Shape =", array_c.shape, "\n", array_c)

array_d = np.reshape(array_a, [3, 3])
print("Shape =", array_d.shape, "\n", array_d)

Shape = (9,) 
 [1 2 3 4 5 6 7 8 9]
Shape = (1, 9) 
 [[1 2 3 4 5 6 7 8 9]]
Shape = (9, 1) 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape = (3, 3) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Concatenate arrays** using `np.concatenate`

In [16]:
array_a = np.full([2, 3], 0)
print("array_a:\n", array_a)

array_b = np.full([2, 3], 1)
print("array_b:\n", array_b)

array_c = np.concatenate([array_a, array_b], axis=1)
print("array_c:\n", array_c)

array_d = np.concatenate([array_a, array_b], axis=0)
print("array_d:\n", array_d)

array_a:
 [[0 0 0]
 [0 0 0]]
array_b:
 [[1 1 1]
 [1 1 1]]
array_c:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
array_d:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


**Split an array** using `np.split`

In [25]:
array_a = np.random.randint(0, 10, [3,4])
print("array_a:\n", array_a)

array_b, array_c = np.split(array_a, [2], axis=1)
print("array_b:\n", array_b, "\narray_c:\n", array_c)

array_d, array_e = np.split(array_a, [2], axis=0)
print("array_d:\n", array_d, "\narray_e:\n", array_e)

array_a:
 [[0 0 4 2]
 [9 6 7 7]
 [3 1 2 1]]
array_b:
 [[0 0]
 [9 6]
 [3 1]] 
array_c:
 [[4 2]
 [7 7]
 [2 1]]
array_d:
 [[0 0 4 2]
 [9 6 7 7]] 
array_e:
 [[3 1 2 1]]


## Aggregation functions 

NumPy provides built-in aggregation functions to work with arrays, which are much more efficient than the built-in Python functions. Therefore, it is optimal to use the NumPy version of these aggregates whenever possible.

Compute the **sum of the values** in an array using `np.sum`

In [49]:
# One-dimensional array
array_a = np.arange(1, 10, 1)
print(array_a)

print("Sum:", np.sum(array_a))

[1 2 3 4 5 6 7 8 9]
sum: 45


In [51]:
# Multi-dimensional array
array_a = np.random.randint(1, 10, [3,4])
print(array_a)

print("Row sum:", np.sum(array_a, axis=1))
print("Column sum:", np.sum(array_a, axis=0))

[[2 1 6 3]
 [7 7 5 7]
 [7 2 9 5]]
Row sum: [12 26 23]
Column sum: [16 10 20 15]


Compute the **maximum value** in an array using `np.max`

In [53]:
# One-dimensional array
array_a = np.arange(1, 10, 1)
print(array_a)

print("Max:", np.max(array_a))

[1 2 3 4 5 6 7 8 9]
Max: 9


In [54]:
# Multi-dimensional array
array_a = np.random.randint(1, 10, [3,4])
print(array_a)

print("Row max:", np.max(array_a, axis=1))
print("Column max:", np.max(array_a, axis=0))

[[5 7 3 8]
 [6 1 5 3]
 [2 4 6 7]]
Row max: [8 6 7]
Column max: [6 7 6 8]


Compute the **minimum value** in an array using `np.min`

In [52]:
# One-dimensional array

array_a = np.arange(1, 10, 1)
print(array_a)

print("Min:", np.min(array_a))

[1 2 3 4 5 6 7 8 9]
Min: 1


In [55]:
# Multi-dimensional array
array_a = np.random.randint(1, 10, [3,4])
print(array_a)

print("Row min:", np.min(array_a, axis=1))
print("Column min:", np.min(array_a, axis=0))

[[7 6 1 2]
 [4 6 6 1]
 [4 7 6 8]]
Row min: [1 1 4]
Column min: [4 6 1 1]


## Other useful functions

* **Product** of elements: `np.prod`
* **Mean** of elements: `np.mean`
* **Median** of elements: `np.median`
* **Standard deviation** of elements:` np.std`
* **Variance** of elements: `np.var`
* **Index of minimum** value: `np.argmin`
* **Index of maximum** value: `np.argmax`
* **Rank-based statistics** of elements: `np.percentile`
* Evaluate whether **any elements are true**: `np.any`
* Evaluate whether **all elements are true**: `np.all`

## Broadcasting arrays

The term broadcasting describes how numpy **treats arrays with different shapes** during arithmetic operations: subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

Broadcasting provides a means of **vectorizing array operations** so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an **element-by-element** basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [31]:
array_a = np.array([1, 2, 3])
print("array_a:\n", array_a)

scalar_a = np.array([2, 2, 2])
print("scalar_a:\n", scalar_a)

array_c = array_a * scalar_a
print("array_c:\n", array_c)

array_a:
 [1 2 3]
scalar_a:
 [2 2 2]
array_c:
 [2 4 6]


NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when **an array and a scalar** are combined in an operation. 

We can think of scalar_a being **stretched during the operation** into an array with the same shape as array_a (the new elements in scalar_a are simply copies of the original scalar). The result is equivalent to the previous example where the scalar was an array. 

The **stretching is only conceptual**. NumPy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible. The code in the second example is more efficient than that in the first because broadcasting moves less memory around during the multiplication (scalar_a is a scalar rather than an array).

In [30]:
array_a = np.array([1, 2, 3])
print("array_a:\n", array_a)

scalar_a = 2 
print("scalar_a:\n", scalar_a)

array_b = scalar_a * array_a 
print("array_b:\n", array_b)

array_a:
 [1 2 3]
scalar_a:
 2
array_b:
 [2 4 6]


More generally, when operating on two arrays, the broadcasting rules are as follows:

*  NumPy compares their **shapes element-wise**: it starts with the trailing dimensions and works its way forward.
* Two **dimensions are compatible** when: they are equal, or one of them is 1. If these conditions are not met, a ValueError is thrown. 
* When **either of the dimensions compared is one**, the other is used: dimensions with size 1 are stretched to match the other.
* Arrays do not need to have the **same number of dimensions**.

In [42]:
# Example 1:
array_a = np.random.randint(0, 10, [5, 4])
print("array_a: ndim=", array_a.ndim, "shape=", array_a.shape)

array_b = np.random.randint(0, 10, [4, ])
print("array_b: ndim=", array_b.ndim, "shape=", array_b.shape)

array_c = array_a * array_b
print("array_c: ndim=", array_c.ndim, "shape=", array_c.shape)

array_a: ndim= 2 shape= (5, 4)
array_b: ndim= 1 shape= (4,)
array_c: ndim= 2 shape= (5, 4)


In [40]:
# Example 2:
array_a = np.random.randint(0, 10, [5, 4])
print("array_a: ndim=", array_a.ndim, "shape=", array_a.shape)

array_b = np.random.randint(0, 10, [1, ])
print("array_b: ndim=", array_b.ndim, "shape=", array_b.shape)

array_c = array_a * array_b
print("array_c: ndim=", array_c.ndim, "shape=", array_c.shape)

array_a: ndim= 2 shape= (5, 4)
array_b: ndim= 1 shape= (1,)
array_c: ndim= 2 shape= (5, 4)


In [44]:
# Example 3:
array_a = np.random.randint(0, 10, [15, 3, 5])
print("array_a: ndim=", array_a.ndim, "shape=", array_a.shape)

array_b = np.random.randint(0, 10, [3, 5])
print("array_b: ndim=", array_b.ndim, "shape=", array_b.shape)

array_c = array_a * array_b
print("array_c: ndim=", array_c.ndim, "shape=", array_c.shape)

array_a: ndim= 3 shape= (15, 3, 5)
array_b: ndim= 2 shape= (3, 5)
array_c: ndim= 3 shape= (15, 3, 5)


In [43]:
# Example 4:
array_a = np.random.randint(0, 10, [15, 3, 5])
print("array_a: ndim=", array_a.ndim, "shape=", array_a.shape)

array_b = np.random.randint(0, 10, [15, 1, 5])
print("array_b: ndim=", array_b.ndim, "shape=", array_b.shape)

array_c = array_a * array_b
print("array_c: ndim=", array_c.ndim, "shape=", array_c.shape)

array_a: ndim= 3 shape= (15, 3, 5)
array_b: ndim= 3 shape= (15, 1, 5)
array_c: ndim= 3 shape= (15, 3, 5)


In [45]:
# Example 5:
array_a = np.random.randint(0, 10, [15, 3, 5])
print("array_a: ndim=", array_a.ndim, "shape=", array_a.shape)

array_b = np.random.randint(0, 10, [3, 1])
print("array_b: ndim=", array_b.ndim, "shape=", array_b.shape)

array_c = array_a * array_b
print("array_c: ndim=", array_c.ndim, "shape=", array_c.shape)

array_a: ndim= 3 shape= (15, 3, 5)
array_b: ndim= 2 shape= (3, 1)
array_c: ndim= 3 shape= (15, 3, 5)
