<a href="https://colab.research.google.com/github/nicoloceneda/Python-edu/blob/master/TensorFlow_Lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow - Lecture 1

---

In [0]:
import tensorflow as tf
import numpy as np

## Creating tensors in TensorFlow
Create a tensor from a **list** or a **NumPy array** using `tf.convert_to_tensor`




In [4]:
a = np.array([1, 2, 3])
tensor_a = tf.convert_to_tensor(a, dtype=tf.int64)
print(tensor_a)

b = [4, 5, 6]
tensor_b = tf.convert_to_tensor(b, dtype=tf.int64)
print(tensor_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([4 5 6], shape=(3,), dtype=int64)


Create a tensor of **constant** values using `tf.constant`



In [11]:
tensor_a = tf.constant([7, 8.0, 9.2], dtype=tf.float64)
print(tensor_a)

tf.Tensor([7.  8.  9.2], shape=(3,), dtype=float32)


Create a tensor of **zeros** using `tf.zeros`

In [5]:
tensor_a = tf.zeros(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[0 0 0]], shape=(1, 3), dtype=int64)


Create a tensor of **ones** using `tf.ones`

In [6]:
tensor_a = tf.ones(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[1 1 1]], shape=(1, 3), dtype=int64)


Create a tensor of **uniformely distributed random** numbers using `tf.random.uniform`

In [7]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[0.31970768 0.99649285 0.22710497]], shape=(1, 3), dtype=float64)


Create a tensor of **normally distributed random** numbers using `tf.random.normal`


In [18]:
tensor_a = tf.random.normal(shape=(1, 3), mean=0.0, stddev=1.0, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[ 0.26917379 -0.90726644  1.20336746]], shape=(1, 3), dtype=float64)


## Manipulating the data type of a tensor
Access the **values** of a tensor using `.numpy()`


In [34]:
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a.numpy())

[1 2 3]


Change the **data type** of a tensor using `tf.cast`

In [8]:
tensor_a1 = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a1)

tensor_a2 = tf.cast(tensor_a1, dtype=tf.float64)
print(tensor_a2)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


## Manipulating the shape of a tensor
**Transpose** a tensor using `tf.transpose`

In [10]:
tensor_a1 = tf.random.uniform(shape=(1, 3), dtype=tf.float64)
tensor_a2 = tf.transpose(tensor_a1)

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (1, 3) --> (3, 1)


**Reshape** a tensor using `tf.reshape`

In [11]:
tensor_a1 = tf.random.uniform(shape=(2, 3), dtype=tf.float64)
tensor_a2 = tf.reshape(tensor_a1, shape=(1, 6))

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (2, 3) --> (1, 6)


**Split** a tensor into a list of equally sized tensors using `tf.split`

In [56]:
# Providing the number of splits (total size of input tensor must be divisible by desired number of splits):
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=3)
print([item.numpy() for item in split_list_a])

tf.Tensor([4 8 2 7 6 6], shape=(6,), dtype=int64)
[array([4, 8]), array([2, 7]), array([6, 6])]


In [57]:
# Providing the sizes of different splits:
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=[3, 2, 1])
print([item.numpy() for item in split_list_a])

tf.Tensor([9 4 7 0 5 9], shape=(6,), dtype=int64)
[array([9, 4, 7]), array([0, 5]), array([9])]


**Concatenate** tensors into a single tensor using `tf.concat`

## Applying mathematical operations to tensors
Compute the **sum** of a tensor using `tf.math.reduce_sum`



In [43]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_sum(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[7.7656752  0.16526041 4.11957462]], shape=(1, 3), dtype=float64)
tf.Tensor([12.05051023], shape=(1,), dtype=float64)


Compute the **mean** of a tensor using `tf.math.reduce_mean`


In [44]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_mean(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[6.99630366 7.9460793  5.65466944]], shape=(1, 3), dtype=float64)
tf.Tensor([6.86568413], shape=(1,), dtype=float64)


Compute the **standard deviation** of a tensor using `tf.math.reduce_std`


In [45]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_std(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[1.90947003 5.76009417 7.5878665 ]], shape=(1, 3), dtype=float64)
tf.Tensor([2.36671935], shape=(1,), dtype=float64)


Compute the **element-wise multiplication** of two tensors using `tf.multiply`

In [20]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.random.normal(shape=(1, 3), mean=0, stddev=1, dtype=tf.float64)
print(tensor_b)

tensor_c = tf.multiply(tensor_a, tensor_b)
print(tensor_c)

tf.Tensor([[1.13994721 0.70768967 0.12669257]], shape=(1, 3), dtype=float64)


Compute the **matrix multiplication** of two tensors using `tf.linalg.matmul`

In [51]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_b = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_c = tf.linalg.matmul(tensor_a, tensor_b, transpose_b=True)

print('shape: ', tensor_a.shape, '*', tensor_b.shape, 'T -->', tensor_c.shape)

shape:  (1, 3) * (2, 3) T --> (1, 2)
