<a href="https://colab.research.google.com/github/nicoloceneda/Python-edu/blob/master/TensorFlow_First_Steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow - First Steps

---

In [0]:
import numpy as np
import tensorflow as tf

## Creating tensors in TensorFlow
Create a tensor from a **list** or a **NumPy array** using `tf.convert_to_tensor`




In [2]:
a = [1, 2, 3]
tensor_a = tf.convert_to_tensor(a, dtype=tf.int64)
print(tensor_a)

b = np.array([4, 5, 6])
tensor_b = tf.convert_to_tensor(b, dtype=tf.int64)
print(tensor_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([4 5 6], shape=(3,), dtype=int64)


Create a tensor of **constant** values using `tf.constant`



In [3]:
tensor_a = tf.constant([7, 8.0, 9.2], dtype=tf.float64)
print(tensor_a)

tf.Tensor([7.  8.  9.2], shape=(3,), dtype=float64)


Create a tensor of **zeros** using `tf.zeros`

In [4]:
tensor_a = tf.zeros(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[0 0 0]], shape=(1, 3), dtype=int64)


Create a tensor of **ones** using `tf.ones`

In [5]:
tensor_a = tf.ones(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[1 1 1]], shape=(1, 3), dtype=int64)


Create a tensor of **uniformely distributed random** numbers using `tf.random.uniform`

In [6]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[0.03809021 0.32745412 0.86464392]], shape=(1, 3), dtype=float64)


Create a tensor of **normally distributed random** numbers using `tf.random.normal`


In [7]:
tensor_a = tf.random.normal(shape=(1, 3), mean=0.0, stddev=1.0, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[ 2.22209128 -0.66700806  1.02025735]], shape=(1, 3), dtype=float64)


## Accessing the values of a tensor
Access the **values** of a tensor using `.numpy()`

In [8]:
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a.numpy())

[1 2 3]


## Manipulating the data type of a tensor
Change the **data type** of a tensor using `tf.cast`

In [9]:
tensor_a1 = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a1)

tensor_a2 = tf.cast(tensor_a1, dtype=tf.float64)
print(tensor_a2)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


## Manipulating the shape of a tensor
**Transpose** a tensor using `tf.transpose`

In [10]:
tensor_a1 = tf.random.uniform(shape=(1, 3), dtype=tf.float64)
tensor_a2 = tf.transpose(tensor_a1)

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (1, 3) --> (3, 1)


**Reshape** a tensor using `tf.reshape`

In [11]:
tensor_a1 = tf.random.uniform(shape=(2, 3), dtype=tf.float64)
tensor_a2 = tf.reshape(tensor_a1, shape=(1, 6))

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (2, 3) --> (1, 6)


**Split** a tensor into a list of equally sized tensors using `tf.split`

In [12]:
# Providing the number of splits (total size of input tensor must be divisible by desired number of splits):
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=3)
print([item.numpy() for item in split_list_a])

tf.Tensor([2 5 2 8 0 1], shape=(6,), dtype=int64)
[array([2, 5]), array([2, 8]), array([0, 1])]


In [13]:
# Providing the sizes of different splits:
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=[3, 2, 1])
print([item.numpy() for item in split_list_a])

tf.Tensor([6 4 0 1 0 4], shape=(6,), dtype=int64)
[array([6, 4, 0]), array([1, 0]), array([4])]


**Concatenate** tensors into a single tensor using `tf.concat`

In [14]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.concat([tensor_a, tensor_b], axis=0)
print(tensor_c)

tf.Tensor([3 5 5], shape=(3,), dtype=int64)
tf.Tensor([9 3 4], shape=(3,), dtype=int64)
tf.Tensor([3 5 5 9 3 4], shape=(6,), dtype=int64)


**Stack** tensors into a single tensor using `tf.stack`

In [15]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.stack([tensor_a, tensor_b], axis=0)
print(tensor_c.numpy())

tf.Tensor([8 3 1], shape=(3,), dtype=int64)
tf.Tensor([1 6 7], shape=(3,), dtype=int64)
[[8 3 1]
 [1 6 7]]


## Applying mathematical operations to tensors
Compute the **sum** of a tensor using `tf.math.reduce_sum`



In [16]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_sum(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[8.62827471 2.36463693 1.62974742]], shape=(1, 3), dtype=float64)
tf.Tensor([12.62265906], shape=(1,), dtype=float64)


Compute the **mean** of a tensor using `tf.math.reduce_mean`


In [17]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_mean(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[9.45091037 0.80590071 4.47610616]], shape=(1, 3), dtype=float64)
tf.Tensor([4.91097241], shape=(1,), dtype=float64)


Compute the **standard deviation** of a tensor using `tf.math.reduce_std`


In [18]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_std(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[6.03496563 6.95232387 2.6456228 ]], shape=(1, 3), dtype=float64)
tf.Tensor([1.85223184], shape=(1,), dtype=float64)


Compute the **element-wise multiplication** of two tensors using `tf.multiply`

In [19]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.random.normal(shape=(1, 3), mean=0, stddev=1, dtype=tf.float64)
print(tensor_b)

tensor_c = tf.multiply(tensor_a, tensor_b)
print(tensor_c)

tf.Tensor([[0.61103818 0.0423364  0.04287361]], shape=(1, 3), dtype=float64)
tf.Tensor([[-0.29351012  0.23099112  0.36445998]], shape=(1, 3), dtype=float64)
tf.Tensor([[-0.17934589  0.00977933  0.01562571]], shape=(1, 3), dtype=float64)


Compute the **matrix multiplication** of two tensors using `tf.linalg.matmul`

In [20]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_b = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_c = tf.linalg.matmul(tensor_a, tensor_b, transpose_b=True)

print('shape: ', tensor_a.shape, '*', tensor_b.shape, 'T -->', tensor_c.shape)

shape:  (1, 3) * (2, 3) T --> (1, 2)
