<a href="https://colab.research.google.com/github/nicoloceneda/Python-edu/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow - Tensors

---

In [0]:
import numpy as np
import tensorflow as tf

## Creating tensors 
Create a tensor of **constant values** from a list or a NumPy array using `tf.convert_to_tensor` or `tf.constant`




In [2]:
# Using tf.convert_to_tensor
tensor_a = tf.convert_to_tensor([1, 2, 3], dtype=tf.int64)
print(tensor_a)

tensor_b = tf.convert_to_tensor(np.array([4, 5, 6]), dtype=tf.int64)
print(tensor_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([4 5 6], shape=(3,), dtype=int64)


In [3]:
# Using tf.constant
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a)

tensor_b = tf.constant(np.array([4, 5, 6]), dtype=tf.int64)
print(tensor_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([4 5 6], shape=(3,), dtype=int64)


Create a tensor of **zeros** using `tf.zeros`

In [4]:
tensor_a = tf.zeros(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[0 0 0]], shape=(1, 3), dtype=int64)


Create a tensor of **ones** using `tf.ones`



In [5]:
tensor_a = tf.ones(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[1 1 1]], shape=(1, 3), dtype=int64)


Create a tensor of **random numbers** using `tf.random`

In [20]:
tf.random.set_seed(seed=1)

tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.random.normal(shape=(1, 3), mean=0.0, stddev=1.0, dtype=tf.float64)
print(tensor_b)

tf.Tensor([[0.32104743 0.04779355 0.33551271]], shape=(1, 3), dtype=float64)
tf.Tensor([[ 2.22804923 -0.25682397  0.08359474]], shape=(1, 3), dtype=float64)


## Accessing the values of a tensor
**Access the values** of a tensor using `.numpy()`

In [7]:
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a.numpy())

[1 2 3]


**Print only the values** of a tensor using `tf.print`

In [21]:
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
tf.print(tensor_a)

[1 2 3]


## Manipulating the data type of a tensor
Change the **data type** of a tensor using `tf.cast`

In [8]:
tensor_a1 = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a1)

tensor_a2 = tf.cast(tensor_a1, dtype=tf.float64)
print(tensor_a2)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


## Manipulating the shape of a tensor
**Transpose** a tensor using `tf.transpose`

In [9]:
tensor_a1 = tf.random.uniform(shape=(1, 3), dtype=tf.float64)
tensor_a2 = tf.transpose(tensor_a1)

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (1, 3) --> (3, 1)


**Reshape** a tensor using `tf.reshape`

In [10]:
tensor_a1 = tf.random.uniform(shape=(2, 3), dtype=tf.float64)
tensor_a2 = tf.reshape(tensor_a1, shape=(1, 6))

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (2, 3) --> (1, 6)


**Split** a tensor into a list of equally sized tensors using `tf.split`

In [22]:
# Providing the number of splits (total size of input tensor must be divisible by desired number of splits):
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=3)
tf.print([item for item in split_list_a])

tf.Tensor([3 2 8 8 7 6], shape=(6,), dtype=int64)
[[3 2], [8 8], [7 6]]


In [23]:
# Providing the sizes of different splits:
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=[3, 2, 1])
tf.print([item for item in split_list_a])

tf.Tensor([6 1 6 7 8 4], shape=(6,), dtype=int64)
[[6 1 6], [7 8], [4]]


**Concatenate** tensors into a single tensor using `tf.concat`

In [13]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.concat([tensor_a, tensor_b], axis=0)
print(tensor_c)

tf.Tensor([1 7 4], shape=(3,), dtype=int64)
tf.Tensor([2 2 3], shape=(3,), dtype=int64)
tf.Tensor([1 7 4 2 2 3], shape=(6,), dtype=int64)


**Stack** tensors into a single tensor using `tf.stack`

In [24]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.stack([tensor_a, tensor_b], axis=0)
tf.print(tensor_c)

tf.Tensor([8 1 1], shape=(3,), dtype=int64)
tf.Tensor([5 5 0], shape=(3,), dtype=int64)
[[8 1 1]
 [5 5 0]]


## Applying mathematical operations to tensors
Compute the **sum** of a tensor using `tf.math.reduce_sum`



In [15]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_sum(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[1.16573154 4.64325697 6.97952886]], shape=(1, 3), dtype=float64)
tf.Tensor([12.78851737], shape=(1,), dtype=float64)


Compute the **mean** of a tensor using `tf.math.reduce_mean`


In [16]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_mean(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[0.84824379 5.16680894 8.03574486]], shape=(1, 3), dtype=float64)
tf.Tensor([4.6835992], shape=(1,), dtype=float64)


Compute the **standard deviation** of a tensor using `tf.math.reduce_std`


In [17]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_std(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[5.3086428  0.97600044 0.29497175]], shape=(1, 3), dtype=float64)
tf.Tensor([2.22042256], shape=(1,), dtype=float64)


Compute the **element-wise multiplication** of two tensors using `tf.math.multiply`

In [18]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.random.normal(shape=(1, 3), mean=0, stddev=1, dtype=tf.float64)
print(tensor_b)

tensor_c = tf.math.multiply(tensor_a, tensor_b)
print(tensor_c)

tf.Tensor([[0.34950163 0.81343061 0.51107586]], shape=(1, 3), dtype=float64)
tf.Tensor([[ 0.63808905 -1.85002     1.73337818]], shape=(1, 3), dtype=float64)
tf.Tensor([[ 0.22301316 -1.50486291  0.88588775]], shape=(1, 3), dtype=float64)


Compute the **matrix multiplication** of two tensors using `tf.linalg.matmul`

In [19]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_b = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_c = tf.linalg.matmul(tensor_a, tensor_b, transpose_b=True)

print('shape: ', tensor_a.shape, '*', tensor_b.shape, 'T -->', tensor_c.shape)

shape:  (1, 3) * (2, 3) T --> (1, 2)
