<a href="https://colab.research.google.com/github/nicoloceneda/Python-edu/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow - Tensors

---

In [0]:
import numpy as np
import tensorflow as tf

## Creating tensors 
Create a tensor from a **list** or a **NumPy array** using `tf.convert_to_tensor`




In [0]:
a = [1, 2, 3]
tensor_a = tf.convert_to_tensor(a, dtype=tf.int64)
print(tensor_a)

b = np.array([4, 5, 6])
tensor_b = tf.convert_to_tensor(b, dtype=tf.int64)
print(tensor_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([4 5 6], shape=(3,), dtype=int64)


Create a tensor of **constant** values using `tf.constant`



In [0]:
tensor_a = tf.constant([7, 8.0, 9.2], dtype=tf.float64)
print(tensor_a)

tf.Tensor([7.  8.  9.2], shape=(3,), dtype=float64)


Create a tensor of **zeros** using `tf.zeros`

In [0]:
tensor_a = tf.zeros(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[0 0 0]], shape=(1, 3), dtype=int64)


Create a tensor of **ones** using `tf.ones`

In [0]:
tensor_a = tf.ones(shape=(1, 3), dtype=tf.int64)
print(tensor_a)

tf.Tensor([[1 1 1]], shape=(1, 3), dtype=int64)


Create a tensor of **uniformely distributed random** numbers using `tf.random.uniform`

In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[0.66893056 0.77203925 0.94050977]], shape=(1, 3), dtype=float64)


Create a tensor of **normally distributed random** numbers using `tf.random.normal`


In [0]:
tensor_a = tf.random.normal(shape=(1, 3), mean=0.0, stddev=1.0, dtype=tf.float64)
print(tensor_a)

tf.Tensor([[-1.02001261 -1.50807849  0.30072968]], shape=(1, 3), dtype=float64)


## Accessing the values of a tensor
Access the **values** of a tensor using `.numpy()`

In [0]:
tensor_a = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a.numpy())

[1 2 3]


## Manipulating the data type of a tensor
Change the **data type** of a tensor using `tf.cast`

In [0]:
tensor_a1 = tf.constant([1, 2, 3], dtype=tf.int64)
print(tensor_a1)

tensor_a2 = tf.cast(tensor_a1, dtype=tf.float64)
print(tensor_a2)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


## Manipulating the shape of a tensor
**Transpose** a tensor using `tf.transpose`

In [0]:
tensor_a1 = tf.random.uniform(shape=(1, 3), dtype=tf.float64)
tensor_a2 = tf.transpose(tensor_a1)

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (1, 3) --> (3, 1)


**Reshape** a tensor using `tf.reshape`

In [0]:
tensor_a1 = tf.random.uniform(shape=(2, 3), dtype=tf.float64)
tensor_a2 = tf.reshape(tensor_a1, shape=(1, 6))

print('shape: ', tensor_a1.shape, '-->', tensor_a2.shape)

shape:  (2, 3) --> (1, 6)


**Split** a tensor into a list of equally sized tensors using `tf.split`

In [0]:
# Providing the number of splits (total size of input tensor must be divisible by desired number of splits):
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=3)
print([item.numpy() for item in split_list_a])

tf.Tensor([0 3 6 6 6 0], shape=(6,), dtype=int64)
[array([0, 3]), array([6, 6]), array([6, 0])]


In [0]:
# Providing the sizes of different splits:
tensor_a = tf.random.uniform(shape=(6, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

split_list_a = tf.split(tensor_a, num_or_size_splits=[3, 2, 1])
print([item.numpy() for item in split_list_a])

tf.Tensor([2 2 4 2 4 2], shape=(6,), dtype=int64)
[array([2, 2, 4]), array([2, 4]), array([2])]


**Concatenate** tensors into a single tensor using `tf.concat`

In [0]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.concat([tensor_a, tensor_b], axis=0)
print(tensor_c)

tf.Tensor([5 6 9], shape=(3,), dtype=int64)
tf.Tensor([4 2 2], shape=(3,), dtype=int64)
tf.Tensor([5 6 9 4 2 2], shape=(6,), dtype=int64)


**Stack** tensors into a single tensor using `tf.stack`

In [0]:
tensor_a = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_a)

tensor_b = tf.random.uniform(shape=(3, ), minval=0, maxval=10, dtype=tf.int64)
print(tensor_b)

tensor_c = tf.stack([tensor_a, tensor_b], axis=0)
print(tensor_c.numpy())

tf.Tensor([0 9 3], shape=(3,), dtype=int64)
tf.Tensor([4 4 7], shape=(3,), dtype=int64)
[[0 9 3]
 [4 4 7]]


## Applying mathematical operations to tensors
Compute the **sum** of a tensor using `tf.math.reduce_sum`



In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_sum(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[0.01748004 6.64492956 6.0802755 ]], shape=(1, 3), dtype=float64)
tf.Tensor([12.74268511], shape=(1,), dtype=float64)


Compute the **mean** of a tensor using `tf.math.reduce_mean`


In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_mean(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[1.86817245 5.33480499 8.99062376]], shape=(1, 3), dtype=float64)
tf.Tensor([5.39786707], shape=(1,), dtype=float64)


Compute the **standard deviation** of a tensor using `tf.math.reduce_std`


In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.math.reduce_std(tensor_a, axis=1)
print(tensor_b)

tf.Tensor([[9.97761395 5.44337844 5.20821818]], shape=(1, 3), dtype=float64)
tf.Tensor([2.19498742], shape=(1,), dtype=float64)


Compute the **element-wise multiplication** of two tensors using `tf.math.multiply`

In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=1, dtype=tf.float64)
print(tensor_a)

tensor_b = tf.random.normal(shape=(1, 3), mean=0, stddev=1, dtype=tf.float64)
print(tensor_b)

tensor_c = tf.math.multiply(tensor_a, tensor_b)
print(tensor_c)

tf.Tensor([[0.89413652 0.99829395 0.85345668]], shape=(1, 3), dtype=float64)
tf.Tensor([[0.61105912 2.12224546 1.18783965]], shape=(1, 3), dtype=float64)
tf.Tensor([[0.54637028 2.1186248  1.01376969]], shape=(1, 3), dtype=float64)


Compute the **matrix multiplication** of two tensors using `tf.linalg.matmul`

In [0]:
tensor_a = tf.random.uniform(shape=(1, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_b = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.float64)
tensor_c = tf.linalg.matmul(tensor_a, tensor_b, transpose_b=True)

print('shape: ', tensor_a.shape, '*', tensor_b.shape, 'T -->', tensor_c.shape)

shape:  (1, 3) * (2, 3) T --> (1, 2)
